[project]
name = "beagleutils"
version = "0.1.0"
description = "Utilities for BEAGLE genotype-likelihood and counts matrices"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

[project.scripts]
geno-utils = "beagleutils.cli:main"

[tool.pytest.ini_options]
addopts = "-q"
